### ISSUE TITLE
Request : Please release one for Kafka cluster

### ISSUE THREAD

**Issue by prawen** [itsaur/zookeeper-docker-swarm#6]
Thanks for the project. Its helpful. Please do the same for Kafka cluster.

**Comment by schaliasos** [comment]
Hi @prawen,

Kafka uses zookeeper for creating a cluster. All needed is to create a zookeeper service and the set the env variable of Kafka service to 

> KAFKA_ZOOKEEPER_CONNECT={{zookeeper_service_name}}:2181

Just replace the zookeeper_service_name to the name of your zookeeper service.

**Example command**

```
docker service create kafka \
       -e KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181 \
       -e KAFKA_BROKER_ID=1 \
       -e HOSTNAME_COMMAND=hostname -i \
       wurstmeister/kafka
```
