### ISSUE TITLE
How to set hostname in zookeeper container?

### ISSUE THREAD

**Issue by wdl5i** [itsaur/zookeeper-docker-swarm#7]
Thanks for the project. Its helpful. But I dont' t know how to set zookeeper hostname , can you give me some help, Thank you!

**Comment by schaliasos** [comment]
Hi @wdl5i, 
this question it is more like a "docker" specific question.

However, you can change the hostname of container by using the the [--hostname](https://docs.docker.com/engine/reference/commandline/service_create/#create-a-service-with-specific-hostname---hostname) argument when creating your service. Just keep in mind that all containers will then have the same hostname.

I am closing this issue as it's not relevant to our docker image.
