### ISSUE TITLE
cronjob gives a lot of defunct processes

### ISSUE THREAD

**Issue by Warmduscher** [itsaur/zookeeper-docker-swarm#8]
first off: Thx for the scripts. Exactly what i was looking for, as i was also not fond, off having multiple zookeeper services in my stack.

I have a small problem though with the trigger.sh starting the 12 backgroundjobs with `&`. When the server runs a long time, the process table is spammed with defunct processes. I think, it would be better to script the crontab with something like:

```
* * * * * sleep 5 && /usr/local/bin/zookeeper-cleanup.sh 1 >> "/var/log/$(date +%Y.%m.%d).log"
* * * * * sleep 10 && /usr/local/bin/zookeeper-cleanup.sh 2 >> "/var/log/$(date +%Y.%m.%d).log"
...
* * * * * sleep 60 && /usr/local/bin/zookeeper-cleanup.sh 12 >> "/var/log/$(date +%Y.%m.%d).log"
```

Could you add this to your images/github or should i fork and merge request?

**Comment by schaliasos** [comment]
@Warmduscher thanks for pointing out, we will check it. It would be also very helpful though, if you could test it yourself and provide a solution with a PR from a forked repo.

@chatsatourian please take care of this.

**Comment by chatsatourian** [comment]
@Warmduscher I have removed the trigger.sh and changed the crontab.txt per your suggestion. Please check the image again and let us know if it is okay so we can close this issue.

**Comment by Warmduscher** [comment]
@chatsatourian thx a lot, as this makes integration in our environment much easier. I'm on training this week without access to our test environment. I will test this on monday in the morning an get back to you.

**Comment by akomlik** [comment]
Why not just launch zookeeper-cleanup.sh in background running sleep/clean endless loop without relying on cron at all?
I made this change and it works just fine.

**Comment by Warmduscher** [comment]
@akomlik For me it is important to not change itsaur's Image. This reduces complexity as i don't have to merge any potential changes into our private gitlab. 
Also having another process running is somewhat error prone. The additional process needs to be monitored and restarted on failure. I know it's easy with i.e. supervisord. But it would add another layer of complexity and increase the image size further.

**Comment by chatsatourian** [comment]
@akomlik the underlying image is alpine, which only has cron for scheduling. As @Warmduscher stated, adding another scheduler would only increase complexity and size. Cron gets the job done, despite the limitation of minute granularity.

**Comment by Warmduscher** [comment]
sorry for the late reply (holiday and other immediate issues in production). I can confirm that reduces the amount of zombies by a large amount. I still get one or two zombies a week, but i think this is a different issue.

thx again for the quick fix.
